trigger:
  - main

pool:
  name: Lab4

variables:
  buildConfiguration: 'Release'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '7.0.410'

  - script: dotnet build PreeQuiz4App/PreeQuiz4App.csproj --configuration $(buildConfiguration)
    displayName: 'Build project'

  - script: dotnet publish PreeQuiz4App/PreeQuiz4App.csproj -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
    displayName: 'Publish project'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
