trigger:
  - main

pool:
  name: Default  # or the name of the agent pool you used

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '7.0.x'

  - script: dotnet build PreeQuiz4App.sln
    displayName: 'Build solution'

  - script: dotnet publish PreeQuiz4App.sln -c Release -o $(Build.ArtifactStagingDirectory)
    displayName: 'Publish app'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
